# Docker Compose override for development
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Development frontend with hot reload
  nlj-frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: nlj_frontend_dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000
      - DOCKER_ENV=true
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      - /app/node_modules  # Anonymous volume to prevent overwriting node_modules
    depends_on:
      nlj-api:
        condition: service_healthy
    networks:
      - nlj_network
    restart: unless-stopped

  # Override API service for development
  nlj-api:
    environment:
      # Frontend URL for development
      - FRONTEND_URL=http://nlj-frontend-dev:5173
      # Enable CORS for development
      - CORS_ORIGINS=http://nlj-frontend-dev:5173,http://localhost:5173,http://localhost:5174
    ports:
      # Expose API port for external access
      - "8000:8000"

  # Enable Kafka UI and other dev tools by default
  kafka-ui:
    profiles: []  # Remove dev-tools profile to always start in dev mode

  # Expose PostgreSQL for development access
  nlj-db:
    ports:
      - "5432:5432"

  # Expose Kafka for development access
  kafka:
    ports:
      - "9092:9092"

  # Expose Elasticsearch for development access
  elasticsearch:
    ports:
      - "9200:9200"

