# LocalStack Configuration for NLJ Platform
# Provides S3 (media storage) and SES (email notifications) for local development


services:
  localstack:
    container_name: nlj-localstack
    # Use Pro image for RDS support - using stable version
    image: localstack/localstack-pro:2.3
    env_file:
      - .env
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      # LocalStack configuration
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localstack
      
      # LocalStack Pro (required for RDS)
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      
      # Services to start
      - SERVICES=s3,ses,rds
      
      # S3 configuration
      - S3_SKIP_SIGNATURE_VALIDATION=1
      - S3_SKIP_KMS_KEY_VALIDATION=1
      
      # SES configuration  
      - SES_PORT=4579
      - SES_SMTP_PORT=25
      
      # Data persistence
      - PERSISTENCE=1
      - DATA_DIR=/var/lib/localstack
      
      # Web UI
      - WEB_UI=1
      - WEB_UI_PORT=8080
      
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack_data:/var/lib/localstack"
      - "./localstack-init:/etc/localstack/init/ready.d"
    networks:
      - nlj_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


networks:
  nlj_network:
    driver: bridge