"""add_multi_stage_workflow_models

Revision ID: dac4479d39ec
Revises: 4a61aa3c207c
Create Date: 2025-07-28 14:34:20.732249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac4479d39ec'
down_revision = '4a61aa3c207c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approval_workflows', sa.Column('template_id', sa.UUID(), nullable=True, comment='Workflow template (if using multi-stage workflow)'))
    op.add_column('approval_workflows', sa.Column('current_stage_order', sa.Integer(), nullable=True, comment='Current stage in multi-stage workflow (1, 2, 3, ...)'))
    op.alter_column('approval_workflows', 'assigned_reviewer_id',
               existing_type=sa.UUID(),
               comment='Currently assigned reviewer (single-stage workflow)',
               existing_comment='Currently assigned reviewer',
               existing_nullable=True)
    op.create_index(op.f('ix_approval_workflows_template_id'), 'approval_workflows', ['template_id'], unique=False)
    op.create_foreign_key(None, 'approval_workflows', 'workflow_templates', ['template_id'], ['id'])
    op.add_column('workflow_reviews', sa.Column('stage_instance_id', sa.UUID(), nullable=True, comment='Specific stage this review belongs to (multi-stage workflows)'))
    op.create_index(op.f('ix_workflow_reviews_stage_instance_id'), 'workflow_reviews', ['stage_instance_id'], unique=False)
    op.create_foreign_key(None, 'workflow_reviews', 'workflow_stage_instances', ['stage_instance_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_reviews', type_='foreignkey')
    op.drop_index(op.f('ix_workflow_reviews_stage_instance_id'), table_name='workflow_reviews')
    op.drop_column('workflow_reviews', 'stage_instance_id')
    op.drop_constraint(None, 'approval_workflows', type_='foreignkey')
    op.drop_index(op.f('ix_approval_workflows_template_id'), table_name='approval_workflows')
    op.alter_column('approval_workflows', 'assigned_reviewer_id',
               existing_type=sa.UUID(),
               comment='Currently assigned reviewer',
               existing_comment='Currently assigned reviewer (single-stage workflow)',
               existing_nullable=True)
    op.drop_column('approval_workflows', 'current_stage_order')
    op.drop_column('approval_workflows', 'template_id')
    # ### end Alembic commands ###